### ISSUE TITLE
Failure when reading provisioning status of ARM template

### ISSUE THREAD

**Issue by mdlopresti** [flexera/flexera-plugins#215]
### Plugin Name
azure_template

### Issue Type
Intermittently having template fail to launch.  exact same cat with exact same configuration options will work about half the time

### Use Case (Feature Request -or- New Plugin Request Only)
Trying to launch an ARM template

### Plugin version (Bug Only)
I think 1.3... here is the top of the template
```
name "Plugin: Azure Template"
# Version: 1.3
type 'plugin'
```

### Code Snippet (Bug Only)
Seems like it is happening around [here](https://github.com/flexera/flexera-plugins/blob/21c39936452611c240835141e17b4879ae0fad87/azure/rs_azure_template/rs_azure_template.rb#L182) sounds like `@resource` is undefined sometimes

### Error Messages (Bug Only)
```
Problem:
  Undefined collection
Origin:
  line: 2100, column: 15
    definition: azure_template.provision_resource
    task: /root
    expression: @resource.provisioningState
Summary:
  Cannot retrieve field provisioningState from undefined collection
Resolution:
  Make sure collection is defined before attempting to retrieve field values from it
```
